services:
  web:
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - '3000:3000' # expose local port
    volumes:
      - ./client/:/usr/src/app # mount local working directory for live reload
      - /usr/src/app/node_modules # mount node_modules for caching
    env_file:
      - client.env
    networks:
      - app-network
    depends_on:
      - server

  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
      args:
        PORT: 4000
    ports:
      - '4000:4000' # expose local port
    environment:
      - PORT=4000
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'curl', '-X', 'POST', 'http://localhost:4000/ping']
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app-network:
    driver: bridge
